In [2]:
import numpy as np
import pandas as pd

# Array Creation 

In [2]:
arr = np.array([[1,2,3],[4,2,5]])
arr

array([[1, 2, 3],
       [4, 2, 5]])

# Printing type of arr object

In [3]:
# Printing type of arr object
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


# Printing array dimensions (axes or dimensions)


In [4]:
# Printing array dimensions (axes or dimensions)
arr.ndim

2

# Printing shape of array


In [5]:
# Printing shape of array
arr.shape

(2, 3)

# Printing size (total number of elements) of array


In [6]:
# Printing size (total number of elements) of array
arr.size

6

# Printing type of elements in array


In [7]:
# Printing type of elements in array
arr.dtype

dtype('int32')

# Creating array from list with type float


In [8]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


# Creating array from tuple


In [9]:
# Creating array from tuple
b = np.array((1 , 3, 2))
b

array([1, 3, 2])

In [10]:
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


# Creating a 3X4 array with all zeros


In [11]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Create a constant value array of complex type


In [12]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')

In [13]:
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


# Create an array with random values

In [14]:
e = np.random.random((2, 2))
print ("\nA random array:\n", e)


A random array:
 [[0.70673766 0.75777335]
 [0.02046139 0.32187658]]


# fill value

In [30]:
e = np.full((2, 2),fill_value=4)
print ("\nA random array:\n", e)


A random array:
 [[4 4]
 [4 4]]


# Identity

In [48]:
i = np.identity(5,dtype='int32')
i

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Create a sequence of 10 values in range 0 to 30


In [15]:
# Create a sequence of 10 values in range 0 to 30
f = np.arange(0,30,5)
print(f)

[ 0  5 10 15 20 25]


# Reshaping 3X4 array to 2X2X3 array


In [16]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
 
newarr = arr.reshape(2, 2, 3)

In [17]:
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Flatten array

In [18]:
# Flatten array: We can use flatten method to get a copy of array collapsed into one dimension.
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
 
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# linspace:

In [19]:
# linspace: returns evenly spaced values within a given interval. num no. of elements are returned.
n = np.linspace(0,50,10)
print(n)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


# arange: 

In [20]:
# arange: returns evenly spaced values within a given interval. step size is specified
# step size is specified.
f = np.arange(0,50,10)
print(f)

[ 0 10 20 30 40]


# Uniform Samples
#### Generate a random sample from a uniform distribution between lower and higher limit values.

In [39]:
u = np.random.uniform(5,10,size = 4)
u

array([9.23798522, 5.80212104, 5.15521029, 7.30397647])

In [40]:
u = np.random.uniform(size = 5)
u

array([0.38473607, 0.34720691, 0.76852063, 0.68778411, 0.38454775])

In [41]:
np.random.uniform(5,10,size = (2,3))

array([[5.55909576, 9.52305193, 5.77477689],
       [5.49420011, 7.40109013, 9.91031319]])

In [139]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 1, 1, 2], dtype=int64))

# random.randint

In [20]:
r = np.random.randint(5,10,10)
r

array([7, 7, 7, 9, 9, 6, 7, 5, 8, 8])

# Random.random

In [23]:
r = np.random.random(10)
r

array([0.02196738, 0.55072336, 0.11382737, 0.28879061, 0.02043896,
       0.82495151, 0.73336521, 0.11078485, 0.50070395, 0.50495493])

# logspace
#### Generate evenly spaced numbers on a log scale.

In [38]:
l = np.logspace(0,2,6,base=2)
l

array([1.        , 1.31950791, 1.74110113, 2.29739671, 3.03143313,
       4.        ])

In [42]:
l = np.logspace(0,10,6,endpoint=True,base=5)
l

array([1.000000e+00, 2.500000e+01, 6.250000e+02, 1.562500e+04,
       3.906250e+05, 9.765625e+06])

In [18]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing array

In [10]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


# Indexing

In [52]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


### Access 2-D Arrays 

In [55]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [56]:
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


### Access 3-D Arrays


In [62]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [60]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
print(arr[1, 0, 2])

9


### Negative Indexing


In [69]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### Step Indexing


In [68]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[::2])

[10 20 30 40]


In [72]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[:2,:2])

[[1 2]
 [6 7]]


In [80]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[:1,::2])

[[1 3 5]]


In [81]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[:2,::2])

[[ 1  3  5]
 [ 6  8 10]]


# Integer array indexing example

In [66]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [67]:
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


# boolean array indexing example


In [24]:
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# basic operations on single array

In [25]:
a = np.array([1, 2, 5, 3])
a+1

array([2, 3, 6, 4])

In [26]:
a-1

array([0, 1, 4, 2])

In [27]:
a*10

array([10, 20, 50, 30])

In [28]:
a**2

array([ 1,  4, 25,  9], dtype=int32)

In [29]:
a*=2

In [30]:
print(a)

[ 2  4 10  6]


# transpose of array

In [31]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [9, 6, 0]])

In [32]:
a.T

array([[1, 3, 9],
       [2, 4, 6],
       [3, 5, 0]])

# unary operators in numpy

In [31]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 9]])

In [34]:
arr.max()

9

In [35]:
arr.max(axis = 0)

array([4, 7, 9])

In [36]:
arr.max(axis = 1)

array([6, 7, 9])

In [32]:
arr.min()

1

In [33]:
arr.min(axis = 0)

array([1, 1, 2])

In [34]:
arr.min(axis = 1)

array([1, 2, 1])

In [35]:
arr.mean()

4.222222222222222

In [37]:
arr.sum()

38

In [54]:
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 9]])

In [55]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [56]:
np.median(arr)

4.0

In [59]:
a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 3.6, 4.7, 5.3])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4], dtype=int64)

# cumulative sum along each row

In [39]:
arr.cumsum(axis = 0)

array([[ 1,  5,  6],
       [ 5, 12,  8],
       [ 8, 13, 17]], dtype=int32)

In [40]:
arr.cumsum(axis = 1)

array([[ 1,  6, 12],
       [ 4, 11, 13],
       [ 3,  4, 13]], dtype=int32)

# binary operators in Numpy

In [41]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])

In [42]:
a+b

array([[5, 5],
       [5, 5]])

In [43]:
a-b

array([[-3, -1],
       [ 1,  3]])

In [44]:
a*b

array([[4, 6],
       [6, 4]])

In [46]:
a

array([[1, 2],
       [3, 4]])

In [47]:
b

array([[4, 3],
       [2, 1]])

In [45]:
a.dot(b) # 1*4+2*2  1*3+2*1
         # 3*4+4*2  3*3+4*1

array([[ 8,  5],
       [20, 13]])

In [89]:
a.sum()

6

# Universal functions (ufunc)

In [48]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
a

array([0.        , 1.57079633, 3.14159265])

In [49]:
np.sin(a)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [50]:
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [51]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

# Data Types

In [84]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [85]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [86]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [87]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [88]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [91]:
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)

Integer Datatype: 
int32


In [92]:
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)


Float Datatype: 
float64


In [93]:
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int64


In [94]:
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]


In [95]:
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)


Addition of Array elements: 
19.0


In [96]:
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)



Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [98]:
c = np.identity(2, dtype = float)

In [99]:
c

array([[1., 0.],
       [0., 1.]])

In [100]:
c = np.identity(4, dtype = float)

In [101]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Expand

In [62]:
arr = np.array([ 8, 14,  1,  8, 11,  4,  9,  4, 1, 13, 13, 11])
np.expand_dims(arr,axis=0)

array([[ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11]])

In [63]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [ 1],
       [13],
       [13],
       [11]])

# Squeeze

In [66]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
np.squeeze(arr)

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 9]])

In [ ]:
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

# Count Non-Zero

In [67]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

# argwhere

In [71]:
a = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
np.argwhere(a>=3)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]], dtype=int64)

In [72]:
array =  np.random.randint(16, size=(4, 4))
print("INPUT ARRAY : \n", array)
print("\nMax element : ", np.argmax(array))

INPUT ARRAY : 
 [[11  9  9 15]
 [ 0  3 11  0]
 [ 7 13 12  9]
 [13  7 11 13]]

Max element :  3


In [74]:
print("\nIndices of Max element : ", np.argmax(array, axis = 0))


Indices of Max element :  [3 2 2 0]


In [76]:
print("\nIndices of Max element : ", np.argmax(array, axis = 1))


Indices of Max element :  [3 2 1 0]


In [78]:
print("\nMin element : ", np.argmin(array))


Min element :  4


In [82]:
print("\nIndices of Min element : ", np.argmin(array, axis = 0))


Indices of Min element :  [1 1 0 1]


In [81]:
print("\nIndices of Min element : ", np.argmin(array, axis = 1))


Indices of Min element :  [1 0 0 1]


In [83]:
np.abs(array)

array([[11,  9,  9, 15],
       [ 0,  3, 11,  0],
       [ 7, 13, 12,  9],
       [13,  7, 11, 13]])

In [84]:
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

In [87]:
np.round(A,decimals=1)

array([[ 1, -3,  4],
       [-2, -4,  3]])

In [88]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

# Clip
#### It is used to keep the values of an array within a range.

In [89]:
arr.clip(0,2)

array([0, 1, 0, 0, 2, 2, 2, 2, 2])

In [90]:
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

In [91]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
np.where(a>5)

# [2][0] ᴇʟᴇᴍᴇɴᴛ (2ɴꜱ ʀᴏᴡ 0ᴛʜ ᴄᴏʟᴜᴍɴ) 6 > 5, ʀᴇᴛᴜʀɴ
# [2][1] ᴇʟᴇᴍᴇɴᴛ (2ɴᴅ ʀᴏᴡ 1ꜱᴛ ᴄᴏʟᴜᴍɴ) 7 > 5, ʀᴇᴛᴜʀɴ
# [3][2] ᴇʟᴇᴍᴇɴᴛ (3ᴅ ʀᴏᴡ 2ɴᴅ ᴄᴏʟᴜᴍɴ) 11 > 5, ʀᴇᴛᴜʀɴ


(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [95]:
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10, 11])

# Put
#### Replaces specified elements of an array with given values.


▪▶ Important params,
a: array,
ind: indices to be replaced.,
v: values to place.

In [96]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [97]:
np.put(arr,[1,2],[6,7])
arr

array([1, 6, 7, 4, 5, 6])

In [98]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [99]:
arr1

array([1, 2, 3])

In [100]:
arr2

array([4, 5, 6])

In [106]:
np.copyto(arr2,arr1)

In [107]:
print("After arr1",arr1)
print("After arr2",arr2)

After arr1 [4 5 6]
After arr2 [4 5 6]


In [108]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([3,4,5,8,9,1])

In [109]:
np.intersect1d(ar1,ar2)

array([1, 3, 4, 5])

In [113]:
ar3 = np.array([1,1,2,3,4,4,5,6,6,7])
np.unique(ar3)

array([1, 2, 3, 4, 5, 6, 7])

In [114]:
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 3, 4])

# setxor1d
### Extracts Unique Elements From Both Arrays
#### setxor1dfunction will return all the unique values from both arrays in sorted order.

In [115]:
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)

array([ 2,  3,  6,  9, 36])

In [116]:
np.union1d(a,b)

array([ 1,  2,  3,  4,  6,  9, 36])

# Splitting
# Horizontal Split

In [117]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,2)

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [118]:
np.hsplit(A,4)

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

# Vertical Split

In [124]:
n = np.vsplit(A,2)
print(n)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]


In [121]:
np.vsplit(A,1)

[array([[3, 4, 5, 2],
        [6, 7, 2, 6]])]

# Stacking
# Horizontal Stacking

In [125]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

# Vertical Stacking

In [126]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [127]:
np.equal(a,b)

array([ True, False, False, False, False])

In [128]:
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

In [129]:
np.tile("Ram",5)

array(['Ram', 'Ram', 'Ram', 'Ram', 'Ram'], dtype='<U3')

In [130]:
np.tile(3,(2,3))

array([[3, 3, 3],
       [3, 3, 3]])

In [131]:
A = np.array([[3, 4, 5, 2],
              [6, 7, 2, 6]])
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1], dtype=int64),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

In [132]:
a = np.array([[2, 4, 6], [4, 8, 12]])
np.percentile(a, 50)

5.0

In [134]:
arr = np.array([2,3,4,1,6,7])
np.percentile(a,5)

2.5

# Standard Deviation and Variance
## std and var are two functions of NumPy that calculates standard deviation and variance along an axis.

In [135]:
a = np.array([[2, 4, 6], [4, 8, 12]])
np.std(a,axis=1)

array([1.63299316, 3.26598632])

In [136]:
np.std(a,axis=0)

array([1., 2., 3.])

In [137]:
np.var(a,axis=1)

array([ 2.66666667, 10.66666667])

In [138]:
np.var(a,axis=0)

array([1., 4., 9.])